### ISSUE TITLE
Exclude files?

### ISSUE THREAD

**Issue by SilentGlasses** [midnightprioriem/mkdocs-autolinks-plugin#18]
Was just wondering if there is a way to add an exclude list to not try to link to files that would allow me to add this as an example of how to use the plugin:
```
[Page Name](page_name.md)
![Image](image.png)
```
but not get these warnings:

```
WARNING -  AutoLinksPlugin unable to find page_name.md in directory /git_repo/docs
WARNING -  AutoLinksPlugin unable to find image.png in directory /git_repo/docs
```

Was thinking in `mkdocs.yml` you can set something like this:

```yml
plugins:
  - search
  - autolinks:
      exclude:
        - page_name.md
        - image.png
```
