### ISSUE TITLE
Incorrect links between pages that are more than two levels deep

### ISSUE THREAD

**Issue by DominikaK** [midnightprioriem/mkdocs-autolinks-plugin#6]
First things first, thank you for the very useful plugin.

I've encountered one issue: links are generated incorrectly between pages that are more than two levels deep.

For example, see part of my `mkdocs.yml` file:

```
nav:
    - Animals:
        - Mammals:
            - Cats:
                - 'test/mammals/cats/cat.md'
            - Dogs:
                - 'test/mammals/dogs/dog.md'
        - Reptiles:
            - Lizards:
                - 'test/reptiles/lizards/lizard.md'
```

A link is generated correctly between pages `cat.md` and `dog.md`.

However, when `cat.md` contains the following link: 

`[Lizard](lizard.md)` 

the generated link looks like this: 

`http://<my_domain>/test/mammals/cats/cat/..../reptiles/lizards/lizard.md`

and the link does not work.
